### PR TITLE
only set submitted if submit succeeded

### LINKED ISSUE #1715: The error message " <!-- a padding to disable MSIE and Chrome friendly error page -->" should not be displayed
## Summary

If the report is not successful to submitted, the user goes back to the previous page and the following message is displayed

error

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

### PR DESCRIPTION
**Pull request by sastels**
Fixes #1715

# Description

Only consider the report submitted if the submission is successful - this means that if the submission fails and the user navigates back to the confirmation page, they will not get the "thank you for submitting" message, but rather have the submit button that will allow them to try again.

To test a bad submission: run locally with `npm run dev` (not `node server.js`). Submissions will fail since you don't have a server running.

# Checklist:

- [x] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [x] I have added and needed tests for my changes (in particular for new screens)
- [x] I have added a comment to any confusing code
- [x] I have added documentation to any modified front-end code. (Or added missing documentation)

### CODE REVIEW

File: f2/src/ConfirmationPage.js [hunk 1]
```diff
@@ -112,7 +112,8 @@ const submitToServer = async (data, dispatch) => {
   console.log('Submitting data:', data)
   const response = await postData('/submit', data)
   const reportId = await response.text()
-  dispatch({ type: 'saveFormData', data: { reportId, submitted: true } })
+  const submitted = reportId && reportId.startsWith('NCFRS-')
```
Comment (amazingphilippe) [inline f2/src/ConfirmationPage.js]: Do we have to make sure it starts with "NCFRS-"? What if the report id prefix gets changed in the future? Could we instead check to see if report id is not an empty string?

Comment (sastels) [reply f2/src/ConfirmationPage.js]: If there is an error on the server we return the error message here instead of an id (kinda hacky... though if there's some sort of critical server error this might be all we get).
