### PR TITLE
delete "English" and "Francais" words in the pop-up message 

### LINKED ISSUE #1564: Please remove word "ENGLISH" and "FRANCAIS" in the pop-up message
## Summary

If the attached file is bigger than 4MB, the pop-up message will be displayed. It will be better if the word "ENGLISH" and "FRANCAIS" are removed

## Steps to reproduce

popup

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

### PR DESCRIPTION
**Pull request by DianeLiu2019**
Fixes #1564 (issue)

deleted "English" and "Francais" words in the pop-up message if attached  is larger than 4MB, also corrected the wrong word"buttom" to "button"

- [ ]x I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)

### CODE REVIEW

File: f2/src/forms/EvidenceInfoForm.js [hunk 1]
```diff
@@ -166,7 +166,7 @@ export const EvidenceInfoForm = props => {
                       variantColor="blue"
                       onChange={onFilesChange}
                     >
-                      <Trans id="evidencePage.addFileButtom" />
+                      <Trans id="evidencePage.addFileButton" />
```
Comment (sastels) [inline f2/src/forms/EvidenceInfoForm.js]: good catch!
