### PR TITLE
FormArrayControl component and Adapters for radios and checkboxes

### LINKED ISSUE #1306: Checkbox arrays are not semantically correct
## Summary

Checkbox arrays are not semantically correct. The input tag does not inherit `name` and `value` properties

As this issue touches all the pages that are using the checkbox array adapter, changes need to be done on multiple pages. It is a good opportunity to clean up and build a component for checkbox arrays. 

Key features:

1. The component will take single checkboxes as childrens
2. You can add as many children as necessary 
3. Single checkboxes will accommodate conditional fields as children as well

## Steps to reproduce

image

image

## Unresolved questions

How might we also bring similar functionality to radio buttons. To evaluate during this issue

### PR DESCRIPTION
**Pull request by amazingphilippe**
Fixes #1306

# Description

Also fixes a tech debt we had in reusing checkbox arrays and radio arrays

# Checklist:

- [ ] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [ ] I have added and needed tests for my changes (in particular for new screens)
- [ ] I have added a comment to any confusing code

# Required followup work

- This code is not tested or linted
- Adding conditional fields in checkbox and radio components. Rather than in the FormArrayControl. More thinking about that

### CODE REVIEW

File: f2/src/components/checkbox/index.js [hunk 1]
```diff
@@ -47,15 +79,18 @@ export const Checkbox = ({ label, isChecked, ...props }) => {
                 {props.children}
               </Text>
             </Flex>
-          </Box>
+
+            {isChecked && (
+              <ConditionalForm>{props.conditionalField}</ConditionalForm>
```
Comment (sastels) [inline f2/src/components/checkbox/index.js]: We might want `props.conditionalField` in the &&, otherwise if there’s no conditional it’ll still make an empty `<ConditionalForm/>`

Comment (amazingphilippe) [reply f2/src/components/checkbox/index.js]: Oh, I had this issue. Good call

**Comment by khalidelaggan** [comment]
Just an FYI, I have this on my todos today for completions 🤞

**Comment by sastels** [comment]
Since this PR breaks the old checkboxes, I think the best idea might be to refactor the other ones into the new format 🙁 . Thoughts?

**Comment by khalidelaggan** [comment]
I will take a look at the failing test shortly then we can   🚢  this

**Comment by khalidelaggan** [comment]
@sastels my local tests are passing, not sure why test is failing in CI?
Screen Shot 2020-02-18 at 12 37 24 PM

File: f2/src/forms/HowDidItStartForm.js [hunk 2]
```diff
@@ -22,13 +22,6 @@ export const HowDidItStartForm = props => {
...
   const howdiditstart = {
     howDidTheyReachYou: [],
-    email: '',
-    phone: '',
-    online: '',
-    application: '',
-    others: '',
-    whenDidItStart: '',
-    howManyTimes: '',
     ...data.formData.howdiditstart,
```
Comment (sastels) [inline f2/src/forms/HowDidItStartForm.js]: I think we need to keep these in - it's giving the app default values for the fields.

File: f2/src/forms/InformationForm.js [hunk 3]
```diff
@@ -28,9 +28,7 @@ export const InformationForm = props => {
   const [data] = useStateValue()
   const information = {
     typeOfInfoReq: [],
-    infoReqOther: '',
     typeOfInfoObtained: [],
-    infoObtainedOther: '',
     tellUsMore: '',
```
Comment (sastels) [inline f2/src/forms/InformationForm.js]: Also keep these default values

File: f2/src/forms/WhatWasAffectedForm.js [hunk 4]
```diff
@@ -36,7 +40,6 @@ export const WhatWasAffectedForm = props => {
   const [data] = useStateValue()
   const whatWasAffected = {
     affectedOptions: [],
-    optionOther: '',
```
Comment (sastels) [inline f2/src/forms/WhatWasAffectedForm.js]: We should keep this default too

File: f2/src/forms/InformationForm.js [hunk 5]
```diff
@@ -180,28 +178,6 @@ export const InformationForm = props => {
...
-                      <A
-                        href={
-                          i18n.locale === 'en'
-                            ? 'https://www.transunion.ca/'
-                            : 'https://www.transunion.ca/fr'
-                        }
-                        isExternal // Opens new tab
-                      />
-                </Trans>
-            </Alert>
```
Comment (sastels) [inline f2/src/forms/InformationForm.js]: keep this alert box

File: f2/src/forms/WhatWasAffectedForm.js [hunk 6]
```diff
@@ -131,26 +111,28 @@ export const WhatWasAffectedForm = props => {
...
+                      <Alert status="warning">
+                        <AlertIcon />
+                        <Trans id="whatWasAffectedForm.warning" />
+                      </Alert>
+                    </Control>
+                ) : null}
+            </FormArrayControl>
+          </Control>
+          <P>
+            <Trans id="whatWasAffectedForm.expectations" />
```
Comment (sastels) [inline f2/src/forms/WhatWasAffectedForm.js]: need translation strings for `whatWasAffectedForm.expectations`

File: f2/src/forms/InformationForm.js (hunk 5 above)
Comment (khalidelaggan) [reply f2/src/forms/InformationForm.js]: Alert is now added back

File: f2/src/forms/WhatWasAffectedForm.js (hunk 4 above)
Comment (khalidelaggan) [reply f2/src/forms/WhatWasAffectedForm.js]: Added

File: f2/src/forms/InformationForm.js (hunk 3 above)
Comment (khalidelaggan) [reply f2/src/forms/InformationForm.js]: Added

File: f2/src/forms/HowDidItStartForm.js (hunk 2 above)
Comment (khalidelaggan) [reply f2/src/forms/HowDidItStartForm.js]: Added

File: f2/src/forms/WhatWasAffectedForm.js (hunk 6 above)
Comment (khalidelaggan) [reply f2/src/forms/WhatWasAffectedForm.js]: the translation string is now added

**Comment by sastels** [comment]
> @sastels my local tests are passing, not sure why test is failing in CI?

Looks like the build is failing because of linting issues:
```
./src/forms/InformationForm.js
  Line 182:14:  'Alert' is not defined      react/jsx-no-undef
  Line 183:16:  'AlertIcon' is not defined  react/jsx-no-undef
  Line 185:18:  'A' is not defined          react/jsx-no-undef
  Line 193:18:  'A' is not defined          react/jsx-no-undef
```

**Comment by khalidelaggan** [comment]
> > @sastels my local tests are passing, not sure why test is failing in CI?
> 
> Looks like the build is failing because of linting issues:
> 
> ```
> ./src/forms/InformationForm.js
>   Line 182:14:  'Alert' is not defined      react/jsx-no-undef
>   Line 183:16:  'AlertIcon' is not defined  react/jsx-no-undef
>   Line 185:18:  'A' is not defined          react/jsx-no-undef
>   Line 193:18:  'A' is not defined          react/jsx-no-undef
> ```

Added

File: f2/src/forms/InformationForm.js [hunk 7]
```diff
@@ -95,72 +78,74 @@ export const InformationForm = props => {
...
-                        )}
-                    </Box>
+                      values.typeOfInfoReq.includes(
+                        'typeOfInfoReq.other',
+                      ) && (
+                        <ConditionalForm>
+                          <Field name="infoReqOther">
+                            {props => (
+                              <FormControl>
+                                <FormLabel htmlFor={key}></FormLabel>
```
Comment (amazingphilippe) [inline f2/src/forms/InformationForm.js]: Is it ok to have empty labels?

**Comment by khalidelaggan** [comment]
@sastels All good now and ready for your final review 👍
