### PR TITLE
Fix missing strings in Who Are You Reporting for page

### LINKED ISSUE #2292: Some strings are missing in Who Are You Reporting for page
## Summary

> Some strings are missing in Who Are You Reporting for page
whoAreYouReportFor1
whoAreYouReportFor2

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

### PR DESCRIPTION
**Pull request by ying-chen-cds**
Fixes #2292 

# Description

> Fix missing strings in Who Are You Reporting for page.

# Any new packages installed?

> Give details

# Required followup work

> Is there anything related to this that still needs to be done (ex: documentation changes).

# Checklist:

- [ ] I have updated the azurescript.sh with any **new environment variables** and added them to the appsettings
- [ ] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [ ] I have added and needed tests for my changes (in particular for new screens)
- [ ] I have added a comment to any confusing code
- [ ] I have added documentation to any modified front-end code. (Or added missing documentation)

### CODE REVIEW

File: f2/server.js [hunk 1]
```diff
@@ -230,7 +230,7 @@ app
         logger.error('ERROR', err)
         throw err
       }
-      submitFeedback(fields.json)
+      submitFeedback(sanitize(fields.json))
```
Comment (justinr86) [inline f2/server.js:233]: Why sanitize here?

Comment (ying-chen-cds) [reply f2/server.js]: Not sure why it's there(I probably had a mistake with github). I update the branch and it's gone. Thanks anyway!

**Review by justinr86 — APPROVED** [review]
