### PR TITLE
fix midfeedback dropdown on IE

### LINKED ISSUE #1468: "Is something wrong on this Page?" section is always displayed and cannot be closed on IE and Firefox
## Summary

"Is something wrong on this Page?" section is always displayed and cannot be closed on IE and Firefox

## Steps to reproduce

error5

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

### PR DESCRIPTION
**Pull request by sastels**
Fixes #1468 

# Description

change the dropdown feedback box into a form that appears and disappears when button is clicked.

Verified on IE11 via BrowserStack.

# Checklist:

- [x] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [x] I have added and needed tests for my changes (in particular for new screens)
- [x] I have added a comment to any confusing code

### CODE REVIEW

File: f2/src/forms/MidFeedbackForm.js [hunk 1]
```diff
@@ -60,8 +61,9 @@ export const MidFeedbackForm = props => {
           </InfoCard>
         </Row>
       ) : (
-        <Box as="details">
+        <Box>
           <Button
```
Comment (amazingphilippe) [inline f2/src/forms/MidFeedbackForm.js]: The button is rendered `as="summary"` rendering it inaccessible with keyboard navigation.  Just removing this prop should fix this i believe. I also want to see how voice over reacts to clicking on the button. See #1551 for similar solution!
