### PR TITLE
remove submissionDate from the analyst email

### LINKED ISSUE #1701: remove submissionDate from the analyst email
## Summary

We added `submissionDate` to the report metadata to allow us to search the database for the number of reports submitted already (in case of a reboot). That field isn't needed in the analyst email - we should delete in `formatAnalystEmail()` right after we copy the data.

## Steps to reproduce

submit a report without `LDAP_UID` set and with an email address on the contact info screen. look at the bottom of the analyst report that you get.

### PR DESCRIPTION
**Pull request by kevinyang06**
Fixes #1701 

# Description

> We added submissionDate to the report metadata to allow us to search the database for the number of reports submitted already (in case of a reboot). That field isn't needed in the analyst email - we should delete in formatAnalystEmail() right after we copy the data.

# Any new packages installed?

> no

# Required followup work

> no
# Checklist:

- [ ] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [ ] I have added and needed tests for my changes (in particular for new screens)
- [ ] I have added a comment to any confusing code
- [ ] I have added documentation to any modified front-end code. (Or added missing documentation)

### CODE REVIEW

File: f2/src/utils/formatAnalystEmail.js [hunk 1]
```diff
@@ -30,6 +30,7 @@ const formatReportInfo = data => {
 
   delete data.reportId // we delete the parts of the data object that we've displayed
   delete data.submissionTime // so that at the end we can display the rest and ensure that
+  delete data.submissionDate //submissionDate does not needed in analyst report
   delete data.language // we didn't miss anything
```
Comment (sastels) [inline f2/src/utils/formatAnalystEmail.js]: The three lines of comment before were meant to be read as one long comment, so adding the new one in the middle makes things a bit confusing 😄  More confusing, perhaps, is why we did the three line comment like this in the first place. Could you move those three lines to before all these delete lines? Leaving in the line you added here just as it is.
