### PR TITLE
show "other "( chosen from how did it start page ) in confirmation page "I was contacted other" 

### LINKED ISSUE #1490: choosing "other  " in how did it start page, didn't show "other" in confirmation page  -bug
## Summary

choosing "other  " in how did it start page, didn't show "other" in confirmation page 
 

## Steps to reproduce

1. Go to How did it start page, choose checkbox "other" for how did the suspect reach you.
2. go through to confirmation page. "other" option didn't show in the confirmation page.

### PR DESCRIPTION
**Pull request by DianeLiu2019**
Fixes #1490(issue)
> Please include a summary of the change.
choosing "other " in how did it start page, show "I  was contacted other" in confirmation page Description

# Checklist:
- [ x] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)

# Required followup work
context design" I was contacted other" don't make sense, may need change "other" to "by other means". will discuss the issue with design team.

### CODE REVIEW

**Comment by amazingphilippe** [comment]
Screen Shot 2020-02-21 at 8 14 18 AM

Looks a little funky. @anikbrazeau Any ideas how we can formulate the sentence if Other is selected, but no custom entry is selected? "by other means" ?

File: f2/src/summary/HowDidItStartSummary.js [hunk 1]
```diff
@@ -26,8 +26,8 @@ export const HowDidItStartSummary = props => {
     //Obtain all the array data into the summary array
     howdiditstart.howDidTheyReachYou.map(key =>
       summary.push(
-        key === 'howDidTheyReachYou.others'
-          ? howdiditstart.others
+        key === 'howDidTheyReachYou'
```
Comment (amazingphilippe) [inline f2/src/summary/HowDidItStartSummary.js]: This will always fail, if this is the desired outcome, we do not need this ternary conditional. 
Instead, I would suggest checking if `key === 'howDidTheyReachYou.others' && howdiditstart.others != ''`

**Comment by sastels** [comment]
> Screen Shot 2020-02-21 at 8 14 18 AM
> 
> Looks a little funky. @anikbrazeau Any ideas how we can formulate the sentence if Other is selected, but no custom entry is selected? "by other means" ?


A thought: if we change in lingui the word "other" to "By other means" then it would fix the issue both here as well as changing the checkbox label for "By other means" which might be better than just an "other" label. Plus we wouldn't need any code here for stripping out the "other" and dealing with it specially.

**Comment by amazingphilippe** [comment]
> A thought: if we change in lingui the word "other" to "By other means" then it would fix the issue both here as well as changing the checkbox label for "By other means" which might be better than just an "other" label. Plus we wouldn't need any code here for stripping out the "other" and dealing with it specially.

💯 agree

**Comment by DianeLiu2019** [comment]
> > Screen Shot 2020-02-21 at 8 14 18 AM
> > Looks a little funky. @anikbrazeau Any ideas how we can formulate the sentence if Other is selected, but no custom entry is selected? "by other means" ?
> 
> A thought: if we change in lingui the word "other" to "By other means" then it would fix the issue both here as well as changing the checkbox label for "By other means" which might be better than just an "other" label. Plus we wouldn't need any code here for stripping out the "other" and dealing with it specially.

I discussed the issue with Anik yesterday. and suggested  change the "other" to "By other means" , which it make more sense. She said it doesn't work in French and she  will come up a way to fix the content issue

**Comment by anikbrazeau** [comment]
I think we could just put a title like "Method of contact" since it gets complicated in French and has to match the checkbox for the way it's set up right now.

I can work on fixing this. It's been on my list of wonky content on the review page to fix.

**Comment by DianeLiu2019** [comment]
PR #1540  fixed the issue

**Comment by sastels** [comment]
no I didn't I just fixed the other two places. Basically by copying the code from this PR 😄
