### PR TITLE
Uifix inputspacing

### LINKED ISSUE #706: add space between form hints and text boxes

### LINKED ISSUE #1688: Fields are too close to label
## Summary

The fields are too close to their labels.

Find a systematic way to solve this issue. A field can have up to 2 elements in between: helper text and error messages. Spacing between field should be the same in all these cases:
1. No helper text and no error message
2. Helper text and no error message
3. Helper text and error message
4. Error message and no helper text

## Steps to reproduce

Screen Shot 2020-03-18 at 8 58 40 AM

### PR DESCRIPTION
**Pull request by amazingphilippe**
Fixes #1688 

# Description

Made the field spacing more robust to take into account the many permutations of label, helper text and error message

# Checklist:

- [x] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [x] I have added and needed tests for my changes (in particular for new screens)
- [x] I have added a comment to any confusing code
- [x] I have added documentation to any modified front-end code. (Or added missing documentation)

### CODE REVIEW

File: f2/src/forms/ContactInfoForm.js [hunk 1]
```diff
@@ -45,10 +45,7 @@ export const ContactInfoForm = ({ onSubmit }) => {
   return (
     <React.Fragment>
       {false ? ( // mark ids for lingui
-        <div>
-          <Trans id="contactinfoForm.email.warning" />
-          <Trans id="contactinfoForm.phone.warning" />
-        </div>
+        <div></div>
```
Comment (sastels) [inline f2/src/forms/ContactInfoForm.js]: We can 🔥 this whole `{false .... }` section if there's nothing left to mark for lingui
