### PR TITLE
change "go back" button's height to the same height as "cancel report" button

### LINKED ISSUE #1650: Go back button on cancel page is squished on mobile devices
## Summary

The stacked-full-width button is not respecting the button height and padding. 

## Steps to reproduce

1. Go to cancel a report
2. Switch to mobile view

Screen Shot 2020-03-10 at 11 48 10 AM

### PR DESCRIPTION
**Pull request by DianeLiu2019**
Fixes #1650 (issue)

change "go back" button's height to the same height as "cancel report"… button on confirmCancel page
# Checklist:

- [ x] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)

### CODE REVIEW

File: f2/src/ConfirmCancelPage.js [hunk 1]
```diff
@@ -44,6 +44,7 @@ export const ConfirmCancelPage = () => {
                   onClick={() => history.goBack()}
                   fontSize={{ base: 'lg', md: 'xl' }}
                   color="black"
+                  height="3rem"
                   variant="link"
```
Comment (amazingphilippe) [inline f2/src/ConfirmCancelPage.js]: We can also remove this line!

Comment (DianeLiu2019) [reply f2/src/ConfirmCancelPage.js]: Deleted the unneeded line
