### PR TITLE
remove The City and Province base on the postal code when report anonymous

### LINKED ISSUE #2038: Should City and Province base on PC be removed if it is anonymous report?
## Summary

The City and Province base on the postal code should be removed in the analyst email if the report is an anonymous. It does not make sense to have it because there is no postal code in the report and city/province is already included in the report

file1 (1)

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

### PR DESCRIPTION
**Pull request by DianeLiu2019**
Fixes #2038(issue)

# Description
remove "The City and Province base on the postal code " in the analyst email if the report is an anonymous. also remove " postalCity = 'Location lookup failed'
    and postalProv = 'Location lookup failed' to avoid showing  "Location lookup failed" when report anonymous. 

# Checklist:

- [ ] I have updated the azurescript.sh with any **new environment variables** and added them to the appsettings
- [ x] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [ ] I have added and needed tests for my changes (in particular for new screens)
- [ ] I have added a comment to any confusing code
- [ ] I have added documentation to any modified front-end code. (Or added missing documentation)

### CODE REVIEW

File: f2/src/utils/formatAnalystEmail.js [hunk 1]
```diff
@@ -66,7 +66,7 @@ const formatVictimDetails = (data) => {
   let postalProv = ''
   try {
     let location = zipcodes.lookup(data.location.postalCode)
-    if (location === undefined) {
+    if (data.location.postalCode && location === undefined) {
```
Comment (kevinyang06) [inline f2/src/utils/formatAnalystEmail.js:69]: this cause error in console 'TypeError: Cannot read property 'city' of undefined' 
now with the new condition, the logic try to fetch location.city when it is anonymous report.
