### PR TITLE
make  the page consistent in displaying an error message

### LINKED ISSUE #2325: Should we have the same way to display an error message
## Summary

There is an inconsistent way to display an error message

For example:
On "Who are you reporting for?" Page, we just display simple message in a pink box 
image

But on "When did the incident happen?" page, we display more info in the pink box

image

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

### PR DESCRIPTION
**Pull request by DianeLiu2019**
Fixes #2325(issue)

# Description
 make  the page consistent in displaying an error message
> Please include a summary of the change.

# Any new packages installed?

> Give details

# Required follow up work

> Is there anything related to this that still needs to be done (ex: documentation changes).

# Checklist:

- [ ] I have updated the azurescript.sh with any **new environment variables** and added them to the appsettings
- [x ] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [ ] I have added and needed tests for my changes (in particular for new screens)
- [ ] I have added a comment to any confusing code
- [ ] I have added documentation to any modified front-end code. (Or added missing documentation)

### CODE REVIEW

File: f2/src/forms/WhoAreYouReportForForm.js [hunk 1]
```diff
@@ -11,6 +11,19 @@ import { P } from '../components/formik/paragraph'
 import { NextCancelButtons } from '../components/formik/button'
 import { formDefaults } from './defaultValues'
 import { WhoAreYouReportForFormSchema } from './WhoAreYouReportForFormSchema'
+import { ErrorSummary } from '../components/formik/alert'
+
+const createErrorSummary = (errors) => {
+  const errorSummary = {}
+  if (errors.whoYouReportFor) {
+    errorSummary['whoYouReportFor'] = {
+      label: <Trans id="whoAreYouReportForPage.title" />,
```
Comment (justinr86) [inline f2/src/forms/WhoAreYouReportForForm.js:20]: The link in the ErrorSummary component will scroll to the element with ID **whoYouReportFor**. Right now there is no element with this ID so it simply scrolls to the top. Please update the error message to contain a unique ID so the link will work properly.

Comment (DianeLiu2019) [reply f2/src/forms/WhoAreYouReportForForm.js:20]: Thank you for teaching, fixed it.

**Review by justinr86 — APPROVED** [review]
