### PR TITLE
fix empty label issue

### LINKED ISSUE #2389: Accessibility - Missing form label at Attach supporting evidence page
## Summary

Got an error (missing form label) when run WAVE on Attach supporting evidence page

image

### PR DESCRIPTION
**Pull request by DianeLiu2019**
Fixes #2389(issue)

# Description
fix "empty label" accessibility issue  in attaching supporting evidence page 
> Please include a summary of the change.

# Any new packages installed?

> Give details

# Required followup work

> Is there anything related to this that still needs to be done (ex: documentation changes).

# Checklist:

- [ ] I have updated the azurescript.sh with any **new environment variables** and added them to the appsettings
- [x] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [ ] I have added and needed tests for my changes (in particular for new screens)
- [ ] I have added a comment to any confusing code
- [ ] I have added documentation to any modified front-end code. (Or added missing documentation)

### CODE REVIEW

File: f2/src/components/formik/fileUpload/index.js [hunk 1]
```diff
@@ -18,7 +18,7 @@ export const FileUpload = ({ field, form, onChange, ...props }) => {
     <FormRow>
       <FileInput id={props.id} custom>
         <FormFile.Input accept={acceptableExtensions} onChange={onChange} />
-        <FormFile.Label />
+        <FormFile.Label>lable={props.label}</FormFile.Label>
```
Comment (justinr86) [inline f2/src/components/formik/fileUpload/index.js:21]: This should only include the props label. Please change from `lable={props.label}` to `{props.label}`.

Comment (DianeLiu2019) [reply f2/src/components/formik/fileUpload/index.js]: fixed. Thanks.

**Review by justinr86 — APPROVED** [review]
