### PR TITLE
Attach files to analyst email

### LINKED ISSUE #1433: Attach files to analyst email
## Summary

Attach files to the analyst email if they pass our scans

## Design Detail

Make sure they are encrypted with the rest of the report.

## Unresolved questions

What do we do with files that fail one or more scans?

### PR DESCRIPTION
**Pull request by kevinyang06**
Fixes #1433

# Description

Attach files to the analyst email if they pass our scans

# Any new packages installed?

no

# Checklist:

- [ ] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [ ] I have added and needed tests for my changes (in particular for new screens)
- [ ] I have added a comment to any confusing code

# Required followup work

add file extension

### CODE REVIEW

File: f2/src/utils/encryptedEmail.js [hunk 1]
```diff
@@ -110,10 +136,11 @@ const getAllCerts = uidList => {
   else console.warn('Encrypted Mail: No certs to fetch!')
 }
 
-const encryptAndSend = async (uidList, message) => {
-  if (uidList)
+const encryptAndSend = async (uidList, data, message) => {
```
Comment (sastels) [inline f2/src/utils/encryptedEmail.js]: 🙂 I know you didn’t commit your server.js code because you had hacked it up, but we’ll have to add “data” to the params of encryptAndSend when we call it.

File: f2/src/utils/encryptedEmail.js [hunk 2]
```diff
@@ -110,10 +136,11 @@ const getAllCerts = uidList => {
...
+  if (uidList) {
     uidList.split().forEach(uid => encryptMessage(uid, message, sendMail))
-  else console.warn('Encrypted Mail: No certs to encrypt with!')
+    uidList.split().forEach(uid => encryptFile(uid, data, sendMail))
+  } else console.warn('Encrypted Mail: No certs to encrypt with!')
 }
 
 // getAllCerts(process.env.LDAP_UID)
```
Comment (sastels) [inline f2/src/utils/encryptedEmail.js]: Opps these are comments left over from when I was writing the original code, we can delete them

**Comment by sastels** [comment]
LGTM. running the docker image locally I add two files. The logs look good and I get three encrypted emails (one for the report and two for the files). Can't read any of them though since I don't have an RCMP email account 🤣
