### PR TITLE
Contact form skip and validation pr2185

### LINKED ISSUE #2185: The fields on contact Info page page should be optional
## Summary

The fields (name, email and phone) in contact info page should be optional. If the email or phone is entered, they should be validated.

## Steps to reproduce

1. Start a report
2. At contact info page, enter (name and email) or (name and phone)

Actual result: The error will be displayed 
Expected result: The error should not be displayed and the entered field should be validated

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

### PR DESCRIPTION
**Pull request by dengcn**
Fixes #2185 (The fields on contact Info page page should be optional) 

# Description
Original request was to make email and phone optional during validation of Contact Info Form

On Aug 17, 2020 meeting, team decided to add checkbox of skip Contact Info

-Add checkbox to let user to skip "name, email, phone), once checked, validation will pass no matter there is anything in (name, email, phone) or not. In the meantime, a message will pop up below to explain

-If this checkout is not checked, validation applies that name is required, while either valid email or valid phone can get validation pass to move to next page

> Please include a summary of the change.
Handling Contact Info Form and Valaidation

# Any new packages installed?
No
> Give details
Change list: 
src/forms/ContactInfoForm.js
 src/forms/defaultValues.js
 src/locales/en.json
 src/locales/fr.json
# Required followup work

> Is there anything related to this that still needs to be done (ex: documentation changes).

# Checklist:

- [ ] I have updated the azurescript.sh with any **new environment variables** and added them to the appsettings
- [X ] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [ ] I have added and needed tests for my changes (in particular for new screens)
- [ ] I have added a comment to any confusing code
- [ ] I have added documentation to any modified front-end code. (Or added missing documentation)

### CODE REVIEW

**Comment by dengcn** [comment]
PR2185_SkipContactInfoCheckBox

**Comment by justinr86** [comment]
I still think this needs to be explained to the user. 

One field is marked required and two others are not. I fill in the required field and leave the other two blank. Selecting the submit button displays an error message indicating that I need to fill in required information. 

contactInfo

**Comment by justinr86** [comment]
Once this error message is displayed the warning banner no longer toggles.

**Comment by dengcn** [comment]
Well, we can add a note on top of Full name explaining this. 
"Full name is required and either Email or Phone number is required if you wish not to skip contact details"
Please advice whichever is fit

**Comment by justinr86** [comment]
What is the status of this branch? Since we are refactoring forms should we just close this one and address any updates in the refactored form?

**Comment by dengcn** [comment]
> What is the status of this branch? Since we are refactoring forms should we just close this one and address any updates in the refactored form?

I will update this PR once contact form is merged

**Comment by dengcn** [comment]
This is reimplement this contactinfoForm validation and skip after new related formik forms and components are in master.

After discussion with  Stephanie and business team, it is decided to 
-use SKIP button to bypass validation in 3 fields(fullName, Email, phone)
-Skip button design keep the same as other form
-If Skip button is not clicked, new validation rule is the same as what we discussed earlier 
1)fullName is to be validated
2)either valid email or valid phone will pass
Above 2 must both pass to get to next page

**Comment by dengcn** [comment]
Here is how SKIP and related display look like
PR2185_SampleGUI_SkipButton

File: f2/src/forms/ContactInfoForm.js [hunk 1]
```diff
@@ -6,15 +6,19 @@ import { Trans } from '@lingui/macro'
...
 import { Form, Container, Row } from 'react-bootstrap'
+import { formDefaults } from './defaultValues'
 import { Formik, FieldArray, Field } from 'formik'
 import { Input } from '../components/formik/input'
 import { SkipButton, NextCancelButtons } from '../components/formik/button'
 import { ErrorSummary } from '../components/formik/alert'
 import { ContactInfoFormSchema } from './ContactInfoFormSchema'
 
-export const ContactInfoForm = (props) => {
+export const skipConsentOption = 'contactinfoPage.anonymousskip.yes'
```
Comment (justinr86) [inline f2/src/forms/ContactInfoForm.js:16]: Why is this string exported? It isn't used anywhere.

File: f2/src/forms/ContactInfoFormSchema.js [hunk 2]
```diff
@@ -20,6 +20,13 @@ const contactFormOptions = {
     label: <Trans id="contactinfoPage.hasValidationErrors" />,
     errorMessage: <Trans id="contactinfoPage.hasValidationErrors" />,
   },
+  emailORphone: {
```
Comment (justinr86) [inline f2/src/forms/ContactInfoFormSchema.js:23]: This isn't actually a question on the form.

File: f2/src/forms/defaultValues.js [hunk 3]
```diff
@@ -66,7 +66,7 @@ const formDefaults = {
     fileDescriptions: [],
   },
   location: { postalCode: '', city: '', province: '' },
-  contactInfo: { fullName: '', email: '', phone: '' },
+  contactInfo: { emailORphone: '', fullName: '', email: '', phone: '' },
```
Comment (justinr86) [inline f2/src/forms/defaultValues.js:69]: Why do we need to alter the default values? We are not adding a value to the report.

File: f2/src/forms/ContactInfoForm.js [hunk 4]
```diff
@@ -55,17 +59,19 @@ export const ContactInfoForm = (props) => {
                     title={<Trans id="contactinfoPage.hasValidationErrors" />}
                   />
                 )}
-                {fyiForm ? (
+                <br />
+                <br />
+                {
```
Comment (justinr86) [inline f2/src/forms/ContactInfoForm.js:64]: These curly braces and React.Fragment are not necessary if there is no longer conditional rendering.

File: f2/src/forms/ContactInfoFormSchema.js (hunk 2 above)
Comment (dengcn) [reply f2/src/forms/ContactInfoFormSchema.js:23]: We need to keep this, this is used and referenced  in errorSummary. Otherwise will cause run time error

The other one is not used now, i remove it
"enterContactDetails"

File: f2/src/forms/defaultValues.js (hunk 3 above)
Comment (dengcn) [reply f2/src/forms/defaultValues.js:69]: Removed

File: f2/src/forms/ContactInfoFormSchema.js (hunk 2 above)
Comment (dengcn) [reply f2/src/forms/ContactInfoFormSchema.js:23]: This is referenced by errorSummary, we need to keep, if removed, run time error will come

File: f2/src/forms/ContactInfoForm.js [hunk 5]
```diff
@@ -6,30 +6,30 @@ import { Trans } from '@lingui/macro'
...
 import { Form, Container, Row } from 'react-bootstrap'
+import { formDefaults } from './defaultValues'
 import { Formik, FieldArray, Field } from 'formik'
 import { Input } from '../components/formik/input'
 import { SkipButton, NextCancelButtons } from '../components/formik/button'
 import { ErrorSummary } from '../components/formik/alert'
 import { ContactInfoFormSchema } from './ContactInfoFormSchema'
 
-export const ContactInfoForm = (props) => {
+export const ContactInfoForm = (props, values) => {
```
Comment (justinr86) [inline f2/src/forms/ContactInfoForm.js:16]: Why are we adding a param to this component?

File: f2/src/forms/ContactInfoForm.js [hunk 6]
```diff
@@ -55,17 +61,19 @@ export const ContactInfoForm = (props) => {
                     title={<Trans id="contactinfoPage.hasValidationErrors" />}
                   />
                 )}
-                {fyiForm ? (
+                <br />
```
Comment (justinr86) [inline f2/src/forms/ContactInfoForm.js:64]: We shouldn't use `<br/>` tag unless absolutely necessary. Instead a styled row should be used. See `<FormRow>` in f2\src\components\formik\row\index.js.

File: f2/src/forms/ContactInfoForm.js [hunk 7]
```diff
@@ -39,9 +39,15 @@ export const ContactInfoForm = (props) => {
       ) : null}
       <Formik
         initialValues={contactInfo}
-        validationSchema={validationSchema}
-        onSubmit={(values) => {
-          props.onSubmit(values)
+        onSubmit={async (values, { setErrors }) => {
+          const errors = !fyiForm
+            ? onSubmitValidation(values)
```
Comment (justinr86) [inline f2/src/forms/ContactInfoForm.js:44]: Why manually set errors here? Shouldn't we just set the custom validation like: `validation={validationFunction}`?

File: f2/src/forms/ContactInfoFormSchema.js [hunk 8]
```diff
@@ -57,26 +47,58 @@ const createErrorSummary = (errors) => {
...
-      message: contactFormOptions.phone.errorMessage,
-    }
+  return errorSummary
+}
+
+const fyiValidate = (values) => {
+  const errors = {}
+  const fields = {}
+
+  if (values.email && !addrs(values.email)) {
```
Comment (justinr86) [inline f2/src/forms/ContactInfoFormSchema.js:64]: I don't think the email-addresses module is viable for email address validation. We should use Yup since we already have valid email defined there. You can just call the validate function manually for emails instead of passing the whole thing to Formik.

As the validation stands now invalid emails will be accepted, such as justin.email@a

File: f2/src/forms/ContactInfoFormSchema.js [hunk 9]
```diff
@@ -57,26 +47,58 @@ const createErrorSummary = (errors) => {
...
-    errorSummary['phone'] = {
-      label: contactFormOptions.phone.label,
-      message: contactFormOptions.phone.errorMessage,
-    }
+  return errorSummary
+}
+
+const fyiValidate = (values) => {
+  const errors = {}
+  const fields = {}
```
Comment (justinr86) [inline f2/src/forms/ContactInfoFormSchema.js:62]: Why is a field object required?

File: f2/src/forms/ContactInfoForm.js (hunk 4 above)
Comment (dengcn) [reply f2/src/forms/ContactInfoForm.js:66]: Advice taken, these <br /> and React.Fragment removed

File: f2/src/forms/ContactInfoForm.js (hunk 6 above)
Comment (dengcn) [reply f2/src/forms/ContactInfoForm.js]: Resolved

File: f2/src/forms/ContactInfoFormSchema.js (hunk 2 above)
Comment (dengcn) [reply f2/src/forms/ContactInfoFormSchema.js]: I take out this from this block, and use others to get label and message, will be in next submmision.

File: f2/src/forms/ContactInfoFormSchema.js (hunk 9 above)
Comment (dengcn) [reply f2/src/forms/ContactInfoFormSchema.js]: Solved, no longer use this, new algorism implemented

File: f2/src/forms/ContactInfoFormSchema.js (hunk 8 above)
Comment (dengcn) [reply f2/src/forms/ContactInfoFormSchema.js]: Solved, new fine-tuned TUP validation is in place

File: f2/src/forms/ContactInfoForm.js (hunk 7 above)
Comment (dengcn) [reply f2/src/forms/ContactInfoForm.js]: Replaced with new code submitted

**Review by justinr86 — APPROVED** [review]
