### PR TITLE
Date validation util

### LINKED ISSUE #1800: More date validation on moneylost page
More validation should be added on the date in moneylost page

If the user enters "0" on day, month or year (0-0-0000) --> No error is received. It should give an error "Invalid date" or Start date/month/year must contain a real day/month/year"
If the user enters 30-02-2020 -> no error is received because no 30 on February. It should give an error "Invalid day or Date must contain a real day"
If the user enters 32-3-2020 or 2-13-2020-> the user will receive an error message "Start date must be in the past". It should be "Start date must contain a real day/month" or "Invalid day/month> One paragraph explanation of the bug.

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

### PR DESCRIPTION
**Pull request by amazingphilippe**
Fixes #1800 #1842

# Description

- Added a validation utility for dates
- Tests for dates are moved to the util
- Updated ErrorSummary and FormArrayControl to be able to display multiple errors for one field.
- Updated forms

# New packages:
- [date-fns](https://date-fns.org/docs/Getting-Started)

# Follow up work:

- We could replace date validation messages with default translation, instead of having distinct translations for separate pages. The translations should be identical for both.

# Checklist:

- [x] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [x] I have added and needed tests for my changes (in particular for new screens)
- [x] I have added a comment to any confusing code
- [x] I have added documentation to any modified front-end code. (Or added missing documentation)

### CODE REVIEW

File: f2/src/utils/validateDate.js [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+  if (day > getDaysInMonth(new Date(year, monthIndex)) || day < 1)
+    isDay = 'notDay'
+
+  // month is between 0 and 11
+  if (monthIndex > 11 || monthIndex < 0) isMonth = 'notMonth'
+
+  // is not in the future, while all fields are valid
+  !isMonth && !isDay && !isYear && isFuture(date) && validate.push('isFuture')
+
+  //Year is over 1867 :eyes:
```
Comment (sastels) [inline f2/src/utils/validateDate.js:35]: this is a requirement?

File: f2/src/components/ErrorSummary/ErrorSummary.stories.mdx [hunk 2]
```diff
@@ -19,9 +19,18 @@ import { Trans } from '@lingui/react'
 
 The ErrorSummary component uses final-form validation to assign errors to fields. This can be set in a `validate` function that returns an error object. The object is a list of field names as keys, pointing to lingui ids as values. This function is usually defined before exporting the form component.
 
+When you can have multiple errors on a single field, you can also pass an array to the errors object.
+
```
Comment (sastels) [inline f2/src/components/ErrorSummary/ErrorSummary.stories.mdx:23]: Why are we changing these components?

File: f2/src/utils/__tests__/validateDate.test.js [hunk 3]
```diff
@@ -0,0 +1,137 @@
...
+  it('fails incorrect transaction date in non-Leap year', () => {
+    expected = ['notDay']
+    expect(validateDate('2017', '2', '29')).toEqual(
+      expect.arrayContaining(expected),
+    )
+    expect(validateDate('2019', '02', '29')).toEqual(
+      expect.arrayContaining(expected),
+    )
+  })
+})
```
Comment (sastels) [inline f2/src/utils/__tests__/validateDate.test.js:137]: awesome testing!

File: f2/src/utils/validateDate.js (hunk 1 above)
Comment (amazingphilippe) [reply f2/src/utils/validateDate.js:35]: No, I just don't know why we are accepting dates as far a year 1000, or even year 0001. I don't think this would affect people really, just a troll-barrier-easter-egg. We can remove this condition if we want!

File: f2/src/components/ErrorSummary/ErrorSummary.stories.mdx (hunk 2 above)
Comment (amazingphilippe) [reply f2/src/components/ErrorSummary/ErrorSummary.stories.mdx:23]: To accept multiple errors on field sets. Especially the date field set, where we can have multiple distinct errors.

File: f2/src/utils/validateDate.js (hunk 1 above)
Comment (DianeLiu2019) [reply f2/src/utils/validateDate.js:35]: Actually I feel it is good idea to set  the year 150 years from now. If report input the year before 1867. It probably they made mistake. who can live that long and there was no computer at that time. I also check UK'S antifraud web: https://reporting.actionfraud.police.uk/reporting-form  The effective year is after 1900. That's my opinion. I will post a message  to get other team members opinion

**Comment by amazingphilippe** [comment]
> LGTM! only thought I had was we have `whenDidItStart.error.notDay`, `transactionDate.error.notDay`, etc, maybe we want to change them to just `dateValidation.error.notDay`, etc if they're going to always have the same text. Just an idea.

Yes, Added to follow up work. We have that default.x translation prefix we could use
