### PR TITLE
Fix Google analytics hopefully

### LINKED ISSUE #1281: Google Analytics still flakey
## Summary

GA works locally but not on https://report-a-scam.azurewebsites.net

## Steps to reproduce

Set the env var `REACT_APP_GOOGLE_ANALYTICS_ID` locally and run app. run `npm run dev` and check the GA page. Will see yourself.

Then go to https://report-a-scam.azurewebsites.net. Nothing gets registere on the GA page.

### PR DESCRIPTION
**Pull request by sastels**
Fixes #1281 

# Description

use GA id in docker build

Tested by manually building a docker image using the argument and running locally. Can't really test the GitHub action nor pipeline without running for reals though.

# Checklist:

- [x] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [x] I have added and needed tests for my changes (in particular for new screens)
- [x] I have added a comment to any confusing code

# Required followup work

need to add  `_REACT_APP_GOOGLE_ANALYTICS_ID` to the Azure pipeline's variables

### CODE REVIEW

File: f2/src/TrackPageViews.js [hunk 1]
```diff
@@ -8,9 +8,13 @@ const GA = process.env.REACT_APP_GOOGLE_ANALYTICS_ID
 // debug dumps info the the console
 // testMode doesn't connect to Google, but allows us to perform automated testing of the tracker in our code
 ReactGA.initialize(GA, {
-  debug: false,
+  debug: true,
   testMode: process.env.NODE_ENV !== 'production',
 })
+
+console.log({ GA })
+console.log(`NODE_ENV=${process.env.NODE_ENV}`)
```
Comment (sastels) [inline f2/src/TrackPageViews.js]: remove this debugging stuff after we verify it works
