### PR TITLE
tweak phone number validation and add tests

### LINKED ISSUE #1752: Dev Environment: The validation on the phone number (Enter your contact details page) should be changed
## Summary

When the user enters the phone number in the "Enter your contact details" page, the following format should be accepted
613-234-7900
613 234 7900
6132347900
Currently, only the last format (6132347900) is accepted

phone

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

### PR DESCRIPTION
**Pull request by sastels**
Fixes #1752 and a little bit of #1758 

# Description

Tweak the phone number validation as in
https://www.w3resource.com/javascript/form/phone-no-validation.php

Also added a test for the validation

# Checklist:

- [x] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [x] I have added and needed tests for my changes (in particular for new screens)
- [x] I have added a comment to any confusing code
- [x] I have added documentation to any modified front-end code. (Or added missing documentation)

### CODE REVIEW

File: f2/src/forms/ContactInfoForm.js [hunk 1]
```diff
@@ -15,7 +15,7 @@ import { ErrorSummary } from '../components/ErrorSummary'
 import { Input } from '../components/input'
 import { Field } from '../components/Field'
 
-const validate = (values) => {
+export const validate = (values) => {
```
Comment (sastels) [inline f2/src/forms/ContactInfoForm.js:18]: added the export so we can import it in our test

File: f2/src/forms/ContactInfoForm.js [hunk 2]
```diff
@@ -24,7 +24,9 @@ const validate = (values) => {
   ) {
     errors.email = 'contactinfoForm.email.warning'
   }
-  if (values.phone !== '' && !new RegExp(/^\d{10}$/).test(values.phone)) {
+  // from https://www.w3resource.com/javascript/form/phone-no-validation.php
+  const phoneRegex = /^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$/
```
Comment (amazingphilippe) [inline f2/src/forms/ContactInfoForm.js:28]: You are a regex guru!
