### PR TITLE
go back to previous page

### LINKED ISSUE #1396: Should it go back to previous page when the user clicks on <Go back> option
## Summary

When the user clicks on <go back> option, it should go the previous page

## Steps to reproduce

1. The user enter the info
Start at incident page -> What could be affected page -> How was your personal info affects page -> What happened page
2. At What happened page, the user clicks on <go back> option
Expected result: It should go to "How was your personal info affects" page 
Actual result:  It goes to "What could be affected " page

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

### PR DESCRIPTION
**Pull request by kevinyang06**
Fixes #1396

# Description

> When the user clicks on option, it should go the previous page

# Steps to reproduce

> 1. The user enter the info
Start at incident page -> What could be affected page -> How was your personal info affects page -> What happened page 
2. At What happened page, the user clicks on option
Expected result: It should go to "How was your personal info affects" page
Actual result: It goes to "What could be affected " page

# Any new packages installed?

> no

# Checklist:

- [x] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [x] I have added and needed tests for my changes (in particular for new screens)
- [x] I have added a comment to any confusing code

# Required followup work

> no

### CODE REVIEW

File: f2/src/BusinessPage.js [hunk 1]
```diff
@@ -25,7 +25,7 @@ export const BusinessPage = () => {
         <Page>
           <Layout columns={{ base: 4 / 4, md: 6 / 8, lg: 7 / 12 }}>
             <Stack spacing={10} shouldWrapChildren>
-              <BackButton route="/whatwasaffected">
+              <BackButton onClick={() => history.goBack()}>
                 <Trans id="businessInfoPage.backButton" />
```
Comment (sastels) [inline f2/src/BusinessPage.js]: Are all of our BackButtons now the same? Ie do they all say “go back” and do a history.goBack()? If so, you could move both the onClick and the trans tag into the button.

File: f2/src/BusinessPage.js [hunk 2]
```diff
@@ -25,9 +25,7 @@ export const BusinessPage = () => {
         <Page>
           <Layout columns={{ base: 4 / 4, md: 6 / 8, lg: 7 / 12 }}>
             <Stack spacing={10} shouldWrapChildren>
-              <BackButton route="/whatwasaffected">
-                <Trans id="businessInfoPage.backButton" />
-              </BackButton>
+              <BackButton></BackButton>
```
Comment (sastels) [inline f2/src/BusinessPage.js]: One more thing: Since `BackButton` doesn't have children anymore you can replace 
```
<BackButton></BackButton>
```
with
```
<BackButton />

Comment (kevinyang06) [reply f2/src/BusinessPage.js]: done
