### PR TITLE
Hookup finalfeedback thanks page

### LINKED ISSUE #1592: Confuse info on the thank you page when the victim cancels the report and gives feedback
## Summary

When the victim cancels the report and fills out the feed back, it should go back to "Thank you for trying our new website" page and with an extra sentence "Thank you. We have received your feedback." instead of "Thank you for reporting" with sentence  "Submitting your report…" because the victim has not submitted any report yet

## Steps to reproduce

- Fill out a few pages of report
- Click "Cancel"
- Click "Cancel Report"
- Click " Tell us more"
- Fill out the form and click submit

cancel

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

### PR DESCRIPTION
**Pull request by sastels**
Fixes #1592 

# Description

* submitting final feedback (from Cancel or thanks page) leads to finalfeedbackthanks page
* also took out the back button on the finalfeedback page so it'd work with both cancel and thanks

# Checklist:

- [x] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [x] I have added and needed tests for my changes (in particular for new screens)
- [x] I have added a comment to any confusing code

# Required followup work

We should probably just make our Back buttons do a `history.back()`. Though then they're exactly the same as pressing the browser back button, so is there a point?

### CODE REVIEW

File: f2/src/FinalFeedbackPage.js [hunk 1]
```diff
@@ -42,17 +41,14 @@ export const FinalFeedbackPage = () => {
...
-            </BackButton>
             <H1>
               <Trans id="finalFeedback.title" />
             </H1>
             <FinalFeedbackForm
               onSubmit={data => {
                 submitToServer(data)
                 setState((state.doneFinalFeedback = true))
-                history.push('/thankYouPage')
+                history.push('/finalfeedbackthanks')
```
Comment (amazingphilippe) [inline f2/src/FinalFeedbackPage.js]: Can we add a conditional here that links to finalfeedbackthanks only if state.doneforms is true? That way, we keep what we have now, but we fix the confusing scenario described in #1592

Comment (sastels) [reply f2/src/FinalFeedbackPage.js]: added code so that
- if they've submitted, they go back to the thankyou page that has the report id on it
- if they have cancelled it goes to the "Thank you for helping us improve this service!" page
