### PR TITLE
Duplicate information is displayed in the analyst email

### LINKED ISSUE #1844: Duplicate information is displayed in the analyst email
## Summary

The following information is displayed twice in the analyst email

Report Version
When did it start

Please see the below picture

start

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

### PR DESCRIPTION
**Pull request by kevinyang06**
Fixes #1844

# Description

> The following information is displayed twice in the analyst email

Report Version
When did it start
# Any new packages installed?

> no

# Required followup work

> no

# Checklist:

- [ ] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [ ] I have added and needed tests for my changes (in particular for new screens)
- [ ] I have added a comment to any confusing code
- [ ] I have added documentation to any modified front-end code. (Or added missing documentation)

### CODE REVIEW

File: f2/src/utils/formatAnalystEmail.js [hunk 1]
```diff
@@ -99,6 +100,7 @@ const formatIncidentInformation = (data) => {
   delete data.howdiditstart.howManyTimes
   delete data.howdiditstart.howDidTheyReachYou
   delete data.whatWasAffected.affectedOptions
+  delete data.howdiditstart.whenDidItStart
```
Comment (sastels) [inline f2/src/utils/formatAnalystEmail.js:103]: We don't need to delete this here (it was removed in https://github.com/cds-snc/report-a-cybercrime/blob/master/f2/src/forms/defaultValues.js instead, essentially)
