### PR TITLE
PR2334FixingLocationPageSPacing

### LINKED ISSUE #2334: Location Page Spacing
## Summary

The spacing in between elements on the Location page needs to be updated. The text above the skip button needs more space below. We should have something like **1 rem** below the text.

locationSpacing

## Steps to reproduce

Navigate to the location info page.

## Unresolved questions

N/A

### PR DESCRIPTION
**Pull request by dengcn**
Fixes #2334 

# Description
This is to fix spacing issue introduced in LocationForm.

> Please include a summary of the change.
Implement matching better spacing between row using new formik row

# Any new packages installed?

> Give details

# Required followup work

> Is there anything related to this that still needs to be done (ex: documentation changes).

# Checklist:

- [ ] I have updated the azurescript.sh with any **new environment variables** and added them to the appsettings
- [X ] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [ ] I have added and needed tests for my changes (in particular for new screens)
- [ ] I have added a comment to any confusing code
- [ ] I have added documentation to any modified front-end code. (Or added missing documentation)

### CODE REVIEW

File: f2/src/forms/LocationInfoForm.js [hunk 1]
```diff
@@ -55,24 +56,23 @@ export const LocationInfoForm = (props) => {
               />
             )}
             <Container>
-              <Row>
+              <FormRow>
                 <Trans id="locationinfoPage.skipInfo" />
-              </Row>
-              <Row>
+              </FormRow>
+              <FormRow marginBottom="2rem">
```
Comment (DianeLiu2019) [inline f2/src/forms/LocationInfoForm.js:62]: I compared marginBottom="2rem" and marginBottom="1rem". feel 1rem looks better.

Comment (justinr86) [reply f2/src/forms/LocationInfoForm.js:62]: Yes, 1 rem is consistent with Contact Info form.

File: f2/src/forms/LocationInfoForm.js [hunk 2]
```diff
@@ -55,24 +56,23 @@ export const LocationInfoForm = (props) => {
...
+              <FormRow>
                 {errors.postalCode && (
                   <P color="#dc3545" fontSize="1.25rem" marginBottom="0.5rem">
                     {errors.postalCode}
                   </P>
                 )}
-              </Row>
-              <Row className="form-section">
+              </FormRow>
+              <FormRow className="form-section">
```
Comment (justinr86) [inline f2/src/forms/LocationInfoForm.js:75]: Please remove the className property here. I think it would be a good idea to move away from this now that we are refactoring the components to use  a CSS-in-JS approach.  If there are any style properties this FormRow needs you can pass them directly now.

Comment (dengcn) [reply f2/src/forms/LocationInfoForm.js:75]: advice taken

Comment (dengcn) [reply f2/src/forms/LocationInfoForm.js]: All updated in latest push

**Review by DianeLiu2019 — APPROVED** [review]
LGTM
