### PR TITLE
Reformat postal code

### LINKED ISSUE #1761: Reformat postal code in the summary page, email and database
## Summary

As Stephanie's suggestion, the postal should be reformatted when it is displayed in summary page, analyst email and database regardless on how the user enters
All the letters should be converted to Upper Case and have space such as K1A 2R3
If the user enters k1a3s4 -> It should be K1A 3S4
If the user enters k1a 3s4 -> It should be K1A 3S4
If the user enter K1A3S4 -> It should be K1A 3S4
If the user enter K1a3s4 -> It should be K1A 3S4
....

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

### PR DESCRIPTION
**Pull request by sastels**
Fixes #1761
Also adds some tests as described in #1758 

# Description

Reformat the postal code properly on location info form submission. This will show it correctly on subsequent parts of the flow (ie confirmation page, database, email)

Also added tests for the postal code validation function.

# Checklist:

- [x] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [x] I have added and needed tests for my changes (in particular for new screens)
- [x] I have added a comment to any confusing code
- [x] I have added documentation to any modified front-end code. (Or added missing documentation)

### CODE REVIEW

File: f2/src/forms/LocationInfoForm.js [hunk 1]
```diff
@@ -15,7 +15,7 @@ import { ErrorSummary } from '../components/ErrorSummary'
 import { Input } from '../components/input'
 import { Field } from '../components/Field'
 
-const validate = (values) => {
+export const validate = (values) => {
```
Comment (sastels) [inline f2/src/forms/LocationInfoForm.js:18]: export so we can test it
