### PR TITLE
Fix wrong number of employee in PDF report

### LINKED ISSUE #2400: Number of employee in Business section should be changed in PDF report
## Summary

Number of employee in Business section should be updated in PDF report

image

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

### PR DESCRIPTION
**Pull request by dengcn**
Fixes #2400 (issue)

# Description

> Please include a summary of the change.

# Any new packages installed?

> Give details
This is to fix wrongly extracted/handled employee number at business section in PDF report

# Required followup work

> Is there anything related to this that still needs to be done (ex: documentation changes).

# Checklist:

- [ ] I have updated the azurescript.sh with any **new environment variables** and added them to the appsettings
- [X ] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
- [ ] I have added and needed tests for my changes (in particular for new screens)
- [ ] I have added a comment to any confusing code
- [ ] I have added documentation to any modified front-end code. (Or added missing documentation)

### CODE REVIEW

File: f2/src/pdf/BusinessInfoView.js [hunk 1]
```diff
@@ -39,7 +61,7 @@ export const BusinessInfoView = (props) => {
           />
           <DescriptionItemView
             title="confirmationPage.businessInfo.numberOfEmployee"
-            description={businessInfo.numberOfEmployee}
+            description={numberofEmployeeString}
```
Comment (ying-chen-cds) [inline f2/src/pdf/BusinessInfoView.js:64]: Change Line64 to "description={<Trans id={businessInfo.numberOfEmployee} />}" and it should work. Don't need code from line 18 -39

Comment (dengcn) [reply f2/src/pdf/BusinessInfoView.js:64]: Just tried  "description={lang[businessInfo.numberOfEmployee]}", and creating PDF crushed.   

Since we need to dig into  deeper layer of "lang['analystReport.numberOfEmployee.1To99'] etc, and keep consistent with what is displayed on summary and analyst report, this is why line 18-39 is used for.

Comment (ying-chen-cds) [reply f2/src/pdf/BusinessInfoView.js:64]: I just tried it on my local, it works

Comment (ying-chen-cds) [reply f2/src/pdf/BusinessInfoView.js:64]: Please refer to PR 2434, it seems working well
numberOfEmployee

Comment (dengcn) [reply f2/src/pdf/BusinessInfoView.js]: Tried again, it worked, all pushed

**Review by ying-chen-cds — APPROVED** [review]
